// <auto-generated />
using System;
using ExtratorDocumentos.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExtratorDocumentos.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260713212602_InicialDocumentos")]
    partial class InicialDocumentos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ExtratorDocumentos.Domain.Documento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("CpfDependente")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErroExtracao")
                        .HasColumnType("longtext");

                    b.Property<bool>("Excluido")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ExtraidoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("Papel")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StatusExtracao")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int>("TipoParentesco")
                        .HasColumnType("int");

                    b.Property<int>("VersaoAtual")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj");

                    b.HasIndex("Cpf");

                    b.HasIndex("CpfDependente");

                    b.HasIndex("Excluido");

                    b.HasIndex("Status");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("ExtratorDocumentos.Domain.DocumentoHistorico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int?>("StatusAnterior")
                        .HasColumnType("int");

                    b.Property<int?>("StatusNovo")
                        .HasColumnType("int");

                    b.Property<string>("Usuario")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId");

                    b.ToTable("DocumentoHistoricos");
                });

            modelBuilder.Entity("ExtratorDocumentos.Domain.DocumentoVersao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ChaveStorage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("HashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoConteudo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("Versao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId", "Versao")
                        .IsUnique();

                    b.ToTable("DocumentoVersoes");
                });

            modelBuilder.Entity("ExtratorDocumentos.Domain.EnderecoExtraido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Bairro")
                        .HasColumnType("longtext");

                    b.Property<string>("Cep")
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Cidade")
                        .HasColumnType("longtext");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.Property<string>("Complemento")
                        .HasColumnType("longtext");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DocumentoVersaoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("FonteDocumento")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Logradouro")
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .HasColumnType("longtext");

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj");

                    b.HasIndex("Cpf");

                    b.HasIndex("DocumentoId");

                    b.HasIndex("DocumentoVersaoId");

                    b.ToTable("EnderecosExtraidos");
                });

            modelBuilder.Entity("ExtratorDocumentos.Domain.IdentificacaoExtraida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CategoriaCnh")
                        .HasColumnType("longtext");

                    b.Property<string>("Cnpj")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Confianca")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Cpf")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DadosBrutosJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataEmissao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataPrimeiraHabilitacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataVencimento")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DocumentoVersaoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("EmissorDocumento")
                        .HasColumnType("longtext");

                    b.Property<string>("Folha")
                        .HasColumnType("longtext");

                    b.Property<string>("Livro")
                        .HasColumnType("longtext");

                    b.Property<string>("LocalEmissao")
                        .HasColumnType("longtext");

                    b.Property<string>("MatriculaCertidao")
                        .HasColumnType("longtext");

                    b.Property<string>("MesReferencia")
                        .HasColumnType("longtext");

                    b.Property<string>("Nacionalidade")
                        .HasColumnType("longtext");

                    b.Property<string>("Naturalidade")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeCompleto")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeMae")
                        .HasColumnType("longtext");

                    b.Property<string>("NomePai")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroCliente")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroCnh")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroInstalacao")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroRenach")
                        .HasColumnType("longtext");

                    b.Property<string>("ObservacoesCnh")
                        .HasColumnType("longtext");

                    b.Property<string>("OrgaoEmissor")
                        .HasColumnType("longtext");

                    b.Property<string>("Provedor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("longtext");

                    b.Property<string>("Rg")
                        .HasColumnType("longtext");

                    b.Property<string>("Termo")
                        .HasColumnType("longtext");

                    b.Property<string>("UfEmissao")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ValidadeCnh")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj");

                    b.HasIndex("Cpf");

                    b.HasIndex("DocumentoId")
                        .IsUnique();

                    b.HasIndex("DocumentoVersaoId");

                    b.ToTable("IdentificacoesExtraidas");
                });

            modelBuilder.Entity("ExtratorDocumentos.Domain.DocumentoHistorico", b =>
                {
                    b.HasOne("ExtratorDocumentos.Domain.Documento", "Documento")
                        .WithMany("Historico")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("ExtratorDocumentos.Domain.DocumentoVersao", b =>
                {
                    b.HasOne("ExtratorDocumentos.Domain.Documento", "Documento")
                        .WithMany("Versoes")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("ExtratorDocumentos.Domain.EnderecoExtraido", b =>
                {
                    b.HasOne("ExtratorDocumentos.Domain.Documento", "Documento")
                        .WithMany("Enderecos")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExtratorDocumentos.Domain.DocumentoVersao", "DocumentoVersao")
                        .WithMany()
                        .HasForeignKey("DocumentoVersaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documento");

                    b.Navigation("DocumentoVersao");
                });

            modelBuilder.Entity("ExtratorDocumentos.Domain.IdentificacaoExtraida", b =>
                {
                    b.HasOne("ExtratorDocumentos.Domain.Documento", "Documento")
                        .WithOne("Identificacao")
                        .HasForeignKey("ExtratorDocumentos.Domain.IdentificacaoExtraida", "DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExtratorDocumentos.Domain.DocumentoVersao", "DocumentoVersao")
                        .WithMany()
                        .HasForeignKey("DocumentoVersaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documento");

                    b.Navigation("DocumentoVersao");
                });

            modelBuilder.Entity("ExtratorDocumentos.Domain.Documento", b =>
                {
                    b.Navigation("Enderecos");

                    b.Navigation("Historico");

                    b.Navigation("Identificacao");

                    b.Navigation("Versoes");
                });
#pragma warning restore 612, 618
        }
    }
}
