// <auto-generated />
using System;
using ExtratorDocumentos.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExtratorDocumentos.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260715174155_SchemaSugestaoConceitualCampos")]
    partial class SchemaSugestaoConceitualCampos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ExtratorDocumentos.Domain.Documento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.Property<decimal?>("ConfiancaIdentificacao")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("CpfDependente")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErroExtracao")
                        .HasColumnType("longtext");

                    b.Property<string>("ErroProcessamento")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<bool>("Excluido")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Extensao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("ExtraidoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("ModeloExtracao")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ModeloIdentificacao")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NomeOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("Papel")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ProcessadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ResultadoExtracaoJson")
                        .HasColumnType("longtext");

                    b.Property<string>("ResultadoIdentificacaoJson")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StatusExtracao")
                        .HasColumnType("int");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int?>("TipoDocumentoIdentificado")
                        .HasColumnType("int");

                    b.Property<int>("TipoParentesco")
                        .HasColumnType("int");

                    b.Property<int>("VersaoAtual")
                        .HasColumnType("int");

                    b.Property<string>("VersaoExtrator")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)")
                    .HasDefaultValue("conhecimento_tipo");

                    b.Property<string>("VersaoSchema")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj");

                    b.HasIndex("Cpf");

                    b.HasIndex("CpfDependente");

                    b.HasIndex("Excluido");

                    b.HasIndex("HashSha256")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("HashSha256", "VersaoExtrator", "VersaoSchema");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("ExtratorDocumentos.Domain.DocumentoExtracao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("Confianca")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ErroCodigo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ErroMensagem")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("ModeloExtracao")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ModeloIdentificacao")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("ProcessadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ResultadoJson")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("SimilaridadeTipo")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("TipoDocumentoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TipoDocumentoIdentificado")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("TipoDocumentoSchemaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TipoDocumentoSolicitado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("TipoReutilizado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("VersaoExtrator")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("VersaoSchema")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("TipoDocumentoId");

                    b.HasIndex("TipoDocumentoSchemaId");

                    b.HasIndex("DocumentoId", "TipoDocumentoId", "TipoDocumentoSchemaId", "VersaoExtrator")
                        .IsUnique();

                    b.HasIndex("DocumentoId", "TipoDocumentoSolicitado", "VersaoSchema", "VersaoExtrator");

                    b.ToTable("DocumentoExtracoes");
                });

            modelBuilder.Entity("ExtratorDocumentos.Domain.DocumentoHistorico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int?>("StatusAnterior")
                        .HasColumnType("int");

                    b.Property<int?>("StatusNovo")
                        .HasColumnType("int");

                    b.Property<string>("Usuario")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId");

                    b.ToTable("DocumentoHistoricos");
                });

            modelBuilder.Entity("ExtratorDocumentos.Domain.DocumentoVersao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ChaveStorage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("HashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoConteudo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("Versao")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HashSha256");

                    b.HasIndex("DocumentoId", "Versao")
                        .IsUnique();

                    b.ToTable("DocumentoVersoes");
                });

            modelBuilder.Entity("ExtratorDocumentos.Domain.OpenRouterModelo", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("AceitaArquivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AceitaImagem")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Bloqueado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("ContextoTokens")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("Permitido")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("PrecoEntradaPorMilhaoTokens")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal?>("PrecoSaidaPorMilhaoTokens")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTime>("PrimeiroVistoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PrioridadeExtracao")
                        .HasColumnType("int");

                    b.Property<int>("PrioridadeIdentificacao")
                        .HasColumnType("int");

                    b.Property<bool>("SaidaTexto")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SuportaJson")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("SuportaStructuredOutputs")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UltimoVistoEm")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Ativo");

                    b.HasIndex("Bloqueado");

                    b.HasIndex("Disponivel");

                    b.HasIndex("Permitido");

                    b.HasIndex("UltimoVistoEm");

                    b.ToTable("OpenRouterModelos");
                });

            modelBuilder.Entity("ExtratorDocumentos.Domain.TipoDocumento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AssinaturaEstruturalJson")
                        .HasColumnType("longtext");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("Confirmado")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("Ativo");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Confirmado");

                    b.ToTable("TiposDocumento", (string)null);
                });

            modelBuilder.Entity("ExtratorDocumentos.Domain.TipoDocumentoCampo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AliasesJson")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("CampoPaiId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal?>("Confianca")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("EncontradoNoArquivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ItemTipoDado")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("NomeExibicao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<bool>("Obrigatorio")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ObrigatorioSugerido")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<string>("OrigemSugestao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RegraNormalizacao")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("RegraValidacao")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("TipoDado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<Guid>("TipoDocumentoSchemaId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CampoPaiId");

                    b.HasIndex("TipoDocumentoSchemaId", "Chave")
                        .IsUnique();

                    b.ToTable("TiposDocumentoCampos", (string)null);
                });

            modelBuilder.Entity("ExtratorDocumentos.Domain.TipoDocumentoCampoSugerido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Aprovado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("PrimeiraOcorrenciaEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("QuantidadeOcorrencias")
                        .HasColumnType("int");

                    b.Property<string>("TipoDado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<Guid>("TipoDocumentoId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UltimaOcorrenciaEm")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Aprovado");

                    b.HasIndex("TipoDocumentoId", "Chave")
                        .IsUnique();

                    b.ToTable("TiposDocumentoCamposSugeridos", (string)null);
                });

            modelBuilder.Entity("ExtratorDocumentos.Domain.TipoDocumentoSchema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DocumentoReferenciaId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("GeradoAutomaticamente")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("PublicadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SchemaJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TipoDocumentoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Versao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoReferenciaId");

                    b.HasIndex("Status");

                    b.HasIndex("TipoDocumentoId", "Ativo");

                    b.HasIndex("TipoDocumentoId", "Versao")
                        .IsUnique();

                    b.ToTable("TiposDocumentoSchemas", (string)null);
                });

            modelBuilder.Entity("ExtratorDocumentos.Domain.UsoOpenRouter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("Custo")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<Guid?>("DocumentoExtracaoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("char(36)");

                    b.Property<long>("DuracaoMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Erro")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<string>("ModeloId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RequestId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Sucesso")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("TokensEntrada")
                        .HasColumnType("int");

                    b.Property<int?>("TokensSaida")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoExtracaoId");

                    b.HasIndex("DocumentoId");

                    b.HasIndex("ModeloId");

                    b.HasIndex("Objetivo");

                    b.ToTable("UsosOpenRouter");
                });

            modelBuilder.Entity("ExtratorDocumentos.Domain.DocumentoExtracao", b =>
                {
                    b.HasOne("ExtratorDocumentos.Domain.Documento", "Documento")
                        .WithMany("Extracoes")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExtratorDocumentos.Domain.TipoDocumento", "TipoDocumento")
                        .WithMany("Extracoes")
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ExtratorDocumentos.Domain.TipoDocumentoSchema", "TipoDocumentoSchema")
                        .WithMany("Extracoes")
                        .HasForeignKey("TipoDocumentoSchemaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Documento");

                    b.Navigation("TipoDocumento");

                    b.Navigation("TipoDocumentoSchema");
                });

            modelBuilder.Entity("ExtratorDocumentos.Domain.DocumentoHistorico", b =>
                {
                    b.HasOne("ExtratorDocumentos.Domain.Documento", "Documento")
                        .WithMany("Historico")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("ExtratorDocumentos.Domain.DocumentoVersao", b =>
                {
                    b.HasOne("ExtratorDocumentos.Domain.Documento", "Documento")
                        .WithMany("Versoes")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("ExtratorDocumentos.Domain.TipoDocumentoCampo", b =>
                {
                    b.HasOne("ExtratorDocumentos.Domain.TipoDocumentoCampo", "CampoPai")
                        .WithMany("CamposFilhos")
                        .HasForeignKey("CampoPaiId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ExtratorDocumentos.Domain.TipoDocumentoSchema", "Schema")
                        .WithMany("Campos")
                        .HasForeignKey("TipoDocumentoSchemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CampoPai");

                    b.Navigation("Schema");
                });

            modelBuilder.Entity("ExtratorDocumentos.Domain.TipoDocumentoCampoSugerido", b =>
                {
                    b.HasOne("ExtratorDocumentos.Domain.TipoDocumento", "TipoDocumento")
                        .WithMany("CamposSugeridos")
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("ExtratorDocumentos.Domain.TipoDocumentoSchema", b =>
                {
                    b.HasOne("ExtratorDocumentos.Domain.Documento", "DocumentoReferencia")
                        .WithMany()
                        .HasForeignKey("DocumentoReferenciaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ExtratorDocumentos.Domain.TipoDocumento", "TipoDocumento")
                        .WithMany("Schemas")
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentoReferencia");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("ExtratorDocumentos.Domain.UsoOpenRouter", b =>
                {
                    b.HasOne("ExtratorDocumentos.Domain.DocumentoExtracao", "DocumentoExtracao")
                        .WithMany("UsosOpenRouter")
                        .HasForeignKey("DocumentoExtracaoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ExtratorDocumentos.Domain.Documento", "Documento")
                        .WithMany("UsosOpenRouter")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documento");

                    b.Navigation("DocumentoExtracao");
                });

            modelBuilder.Entity("ExtratorDocumentos.Domain.Documento", b =>
                {
                    b.Navigation("Extracoes");

                    b.Navigation("Historico");

                    b.Navigation("UsosOpenRouter");

                    b.Navigation("Versoes");
                });

            modelBuilder.Entity("ExtratorDocumentos.Domain.DocumentoExtracao", b =>
                {
                    b.Navigation("UsosOpenRouter");
                });

            modelBuilder.Entity("ExtratorDocumentos.Domain.TipoDocumento", b =>
                {
                    b.Navigation("CamposSugeridos");

                    b.Navigation("Extracoes");

                    b.Navigation("Schemas");
                });

            modelBuilder.Entity("ExtratorDocumentos.Domain.TipoDocumentoCampo", b =>
                {
                    b.Navigation("CamposFilhos");
                });

            modelBuilder.Entity("ExtratorDocumentos.Domain.TipoDocumentoSchema", b =>
                {
                    b.Navigation("Campos");

                    b.Navigation("Extracoes");
                });
#pragma warning restore 612, 618
        }
    }
}
